name: Papermage CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  USING_GITHUB_ACTIONS: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.9", "3.8"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install poppler-utils
          pip install --upgrade pip
          pip install -e .[dev,predictors,visualizers]

      - name: Print sys.path
        run: |
          python -c "import sys; print(sys.path)"

      - name: Test with Python ${{ matrix.python-version }}
        run: |
          pytest \
            --cov-fail-under=42 \
            --log-disable=pdfminer.psparser --log-disable=pdfminer.pdfinterp --log-disable=pdfminer.cmapdb --log-disable=pdfminer.pdfdocument --log-disable=pdfminer.pdffont --log-disable=pdfminer.pdfparser --log-disable=pdfminer.converter --log-disable=pdfminer.converter --log-disable=pdfminer.pdfpage \
            --ignore=tests/test_predictors/test_span_qa_predictors.py \
            --ignore=tests/test_predictors/test_bio_tagger_predictor.py
